language: r

r_github_packages:
 - jimhester/robustr
 - jimhester/covr

after_success:
 - Rscript -e 'library(covr); coveralls()'
  
before_script:
 - sudo apt-get install poppler-utils

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Kq59sGf7KtBA91DkrFv7g8tn2TIrkaKk4HZ3xiSn/wm8W337ilpLie3go+i6iZ9hFwtZ22yl6pqgyuyZgn5qmr4PV2/pshvNyNS6M3m+veueXCnID2+rFXNEjvvAOn3zpDARSBXFWMs44y3doD+yQ4tYA3HUUaoJeH60is3LtD8=
